#2#3 implement step method
hpi-www-midl-text-localization/text-localization-environment pull request #4
Opened 2018-11-25 12:46 UTC by J-L-O

I tried to stick to the base paper as closely as possible. The main deviation is that this environment uses the VGG16 network for feature extraction, since the network used in the base paper was not available.

2018-11-25 21:04 UTC, bakoe requested changes
Very nice, thanks for doing this!

I only had some minor complaints, as stated in the review comments.

Apart from that, on a high level, from my point of view the last missing pieces are:

- the special reward calculation necessary for the "trigger" action (see corresponding review comment)
- the "crossing out" (IoR) mechanism invoked by the "trigger" action (see #6 for a follow-up issue I already created for this)

What do you think, shall we include the special reward calculation for the "trigger" action in this PR or should we create a follow-up issue for this as well (similar to #6)?

2018-11-25 21:04 UTC, bakoe commented on environment.py
> +                           }
Any reason why you (a) ordered and (b) named the actions different than in the paper?

<img width="448" alt="image" src="https://user-images.githubusercontent.com/807665/48983781-75455f80-f0f3-11e8-9cf5-f007032f1a99.png">

If there's no specific reason, I'd prefer the following (a) order and (b) naming:

```python
        self.action_set = { 0: self.right,
                            1: self.left,
                            2: self.up,
                            3: self.down,
                            4: self.bigger,
                            5: self.smaller,
                            6: self.fatter,
                            7: self.taller,
                            8: self.trigger }
```

This may, to my mind, help us to debug and/or understand the ML results later on, since we can then directly switch back and forth between the algorithm and the base paper without having to change the order and naming in our minds continuously. :wink:

2018-11-25 21:04 UTC, bakoe commented on environment.py
> +        # self.feature_extractor.to_gpu(0)
I assume that commenting in this line would allow us to enable GPU support, at least for the VGG16 feature extractor? 
- If yes, I'd prefer to **either** have a comment describing that "Enabling the following line will enable GPU support for the feature extractor used" **or** even have a corresponding flag argument in the constructor that allows to enable the GPU support from outside (the latter would be my personal preference). 
- If not, I'd prefer to have the line removed for now, since commented-out code is considered bad practice imho since it could irritate either us or others reading the code.

2018-11-25 21:04 UTC, bakoe commented on environment.py
>          self.alpha = 0.2
Since you made the HISTORY_LENGTH a constant, I'd prefer making the alpha value a constant as well, i. e. by having `ALPHA = 0.2` in the `TextLocEnv`.

2018-11-25 21:04 UTC, bakoe commented on environment.py
> +        self.iou = 0
I'm not sure whether the abbreviation `iou` is the best name for this variable since it may not immediately be understandable. What about using `intersection_over_union` instead? 

However, that's just my personal opinion – using `iou` could be perfectly fine as well.

2018-11-25 21:04 UTC, bakoe commented on environment.py
> +        reward = np.sign(new_iou - self.iou)
According to the base paper, the reward for the terminal action `trigger` has to be calculated in a special way:

<img width="430" alt="image" src="https://user-images.githubusercontent.com/807665/48984060-26012e00-f0f7-11e8-8e7b-85774ae35cf7.png">
<img width="431" alt="image" src="https://user-images.githubusercontent.com/807665/48984063-2ef1ff80-f0f7-11e8-9bde-7399284f5e94.png">

It seems like you did not implement this special reward calculation yet? Maybe we should include it in this PR or create a corresponding follow-up issue?

2018-11-25 21:04 UTC, bakoe commented on environment.py
>      def render(self, mode='human'):
Just a question on the side: What is the `mode` argument for? I know that it has been part of the environment skeleton already … however, I'm still curious. 🙂

2018-11-25 21:04 UTC, bakoe commented on environment.py
> +        croppped = self.image.crop(self.bbox)
Are you sure that this line works, i. e. that the `image.crop()` call succeeds when a np.array like `self.bbox` is passed?

<img width="716" alt="image" src="https://user-images.githubusercontent.com/807665/48984232-a7f25680-f0f9-11e8-810e-2ebcd070dbb0.png">
— https://pillow.readthedocs.io/en/3.1.x/reference/Image.html#PIL.Image.Image.crop

According to [this explanation](https://medium.com/xster-tech/how-to-convert-numpy-array-to-tuple-aedbb6555dcc), we might need to use the following syntax instead:

```suggestion
        croppped = self.image.crop(tuple(self.bbox))
```

2018-11-25 21:04 UTC, bakoe commented on environment.py
>          """Compute the state from the image, the bounding box and the action history"""
At the moment, the action history isn't considered in the state calculation, is it?

2018-11-25 21:04 UTC, bakoe commented on environment.py
>          """Compute the state from the image, the bounding box and the action history"""
This comment was accidentally moved from `def compute_state(self):` to this function (`def extract_features(self):`), wasn't it?

2018-11-25 21:04 UTC, bakoe commented on environment.py
> +        self.state = self.compute_state(), self.history
I'm a little bit confused since both this line and the `compute_state()` function from lines 151..152 …

```python
    def compute_state(self):
         return self.extract_features(), self.history
```

do return the `self.history` value. Isn't `self.state` then containing something like the following?

```
((<return value from extract_features()>, self.history), self.history)
```

2018-11-25 21:04 UTC, bakoe commented on environment.py
> +        delta = directions * adjustments
Pretty cool usage of "Boolean" multiplication 🙂

2018-11-25 21:04 UTC, bakoe commented on environment.py
> +        new_box[3] = min(new_box[3], self.image.height)
Shouldn't both this line and the line above constrain the bottom right co-ordinate of the new bounding box to `self.image.width - 1` and `self.image.height - 1`? Otherwise, we may end up with invalid bounding box co-ordinates when an image is e. g. 256 x 256 pixels large and the bottom right co-ordinate of the new bounding box is put to something like `(256, 20)`, which would be outside of the images' boundaries.

2018-11-25 21:04 UTC, bakoe commented on environment.py
> +        self.adjust_bbox(np.array([-1, -1, 1, 1]))
I'm not super sure whether the bigger and smaller actions (or zoom_in and zoom_out) should have "twice" the total effect (or "impact") as the other actions (which they currently do have – to my mind – due to the current implementation using an absolute sum of actions of 4 instead of 2, as used by the other actions)[1]. I did not find anything related in the base paper, unfortunately. 😢 Did you find something related that suggests using one of the approaches? 

[1] `zoom_out`: abs(-1) + abs(-1)+ abs(1) + abs(1) = 4,
`right`: abs(1) + abs(0) + abs(1) + abs(0) = 2

2018-11-25 21:04 UTC, bakoe commented on environment.py
> +        croppped = self.image.crop(self.bbox)
Typo:

```suggestion
        cropped = self.image.crop(self.bbox)
```

2018-11-25 21:04 UTC, bakoe commented on environment.py
> +        return croppped.resize((224, 224), LANCZOS)
(Typo; see above)

```suggestion
        return cropped.resize((224, 224), LANCZOS)
```

2018-11-25 21:04 UTC, bakoe commented on environment.py
> +        return feature[0]
I'm not sure about the syntax here – are you sure that `feature_extractor.extract(…)["fc7"][0]` returns the feature representation we're looking for?

2018-11-25 21:15 UTC, J-L-O commented on environment.py
> +                           }
Makes sense, I'm going to change it

2018-11-25 21:16 UTC, J-L-O commented on environment.py
> +        # self.feature_extractor.to_gpu(0)
The flag solution is definitely the best, yes

2018-11-25 21:16 UTC, J-L-O commented on environment.py
>          self.alpha = 0.2
I agree

2018-11-25 21:18 UTC, J-L-O commented on environment.py
> +        self.iou = 0
I was kind of unsure about that, `intersection_over_union` is a bit long imo, but it might still be better, yes

2018-11-25 21:19 UTC, J-L-O commented on environment.py
> +        reward = np.sign(new_iou - self.iou)
I also realized that later, it's already fixed

2018-11-25 21:21 UTC, bakoe commented on environment.py
>          self.alpha = 0.2
(does apply to the newly introduced constants (namely tau – τ and eta – η) as well 🙂)

2018-11-25 21:23 UTC, bakoe commented on environment.py
>          self.alpha = 0.2
Actually, I'd really like having a one-line comment that (a) explains the semantic and (b) uses the original greek letter as in the base paper for the values of ALPHA, TAU and ETA:

```python
# ⍺: factor relative to the current box size that is used for every transformation action
ALPHA = 0.2
```
etc.

2018-11-25 21:24 UTC, J-L-O commented on environment.py
>      def render(self, mode='human'):
I don't really get it either, most predefined environments ignore the argument just like we do. The atari_env offers two modes, so you might want to look into that if you want find out more

2018-11-25 21:25 UTC, bakoe commented on environment.py
> +        self.iou = 0
Hmm, it's really quite long, especially concerning that we have multiple methods as well which could/should use the long name as part of their function name then as well.

Maybe we should just stick to `iou` then – I don't know.

If we had doc comments to the functions, we could easily explain the meaning of `iou` there as well, e. g. in a doc comment for the `compute_best_iou()` method. Hmm … 😉

2018-11-25 21:25 UTC, J-L-O commented on environment.py
> +        croppped = self.image.crop(self.bbox)
Well, it definitely works right now, however your suggestion might be cleaner

2018-11-25 21:26 UTC, J-L-O commented on environment.py
>          """Compute the state from the image, the bounding box and the action history"""
Yep

2018-11-25 21:27 UTC, bakoe commented on environment.py
> +        croppped = self.image.crop(self.bbox)
As we are at "it definitely works right now" – is there any way to actually test out the environment right now? Like some sort of debug/interactive mode for OpenAI gym environments that one could use to manually trigger the actions and e. g. continuously render the resulting image?

2018-11-25 21:28 UTC, J-L-O commented on environment.py
> +        self.adjust_bbox(np.array([-1, -1, 1, 1]))
No, the paper doesn't say anything about that. I guess we should just use whatever turns out to give better results

2018-11-25 21:32 UTC, J-L-O commented on environment.py
> +        return croppped.resize((224, 224), LANCZOS)
Fixed

2018-11-25 21:42 UTC, J-L-O commented on environment.py
> +        new_box[3] = min(new_box[3], self.image.height)
The `Image.crop()` function excludes the last pixel, if you take a 256x256 image and say `img.crop((0, 0, 255, 255))` you cut of the last row/column

2018-11-25 21:49 UTC, J-L-O commented on environment.py
> +        croppped = self.image.crop(self.bbox)
Right now I just manually call the step() and render() functions.

2018-11-25 21:49 UTC, J-L-O commented on environment.py
> +        self.state = self.compute_state(), self.history
True, fixed

2018-11-25 23:37 UTC, bakoe approved these changes

2018-11-26 09:32 UTC, bakoe commented
Thanks for integrating the review feedback, @J-L-O! From my point of view, the PR is ready to merge! 

PS: We may use "Squash and Merge" in order to keep the commit history of the master branch somewhat clean:

<img width="337" alt="image" src="https://user-images.githubusercontent.com/807665/49005243-87acb100-f166-11e8-8344-bf00fa4deeb0.png">

2018-11-26 18:51 UTC, merged